### ISSUE TITLE
Centrifugo subscribe to mutiple channel issue

### ISSUE THREAD

**Issue by deepak2431** [centrifugal/examples#16]
I am trying to subscribe to multiple tokens using centrifugo but I am getting some issue:
1. If I remove the setTimeout function it doesn't connect and give error as couldn't connect. Do I need to compulsory use setTimeOut in case of subscription to multiple tokens?
2.  On using with setTimeout each time I get the last channel name instead of current channel ? Here's the link to code  [Code sample](https://gist.github.com/deepak2431/4a04b7a0e8147a432e9d5268b53a2540)

Please help out me with this as I have referred this https://github.com/centrifugal/centrifuge/issues/50 but still it's not working perfectly for me.

Thanks in advance!

**Comment by deepak2431** [comment]
@FZambia  Please have a look into it!

**Comment by FZambia** [comment]
@deepak2431 hi, could you post an self-contained example without React involved? Like ready to use `index.html` file - so that I could easily run it. I am not sure I fully understand questions - so would be nice to see a more detailed step-by-step description.

**Comment by deepak2431** [comment]
Here's link to app https://stackblitz.com/edit/react-dynwdy

I have mentioned as comments in the code what issue I am facing. The data is only received till 3:15 IST.

**Comment by FZambia** [comment]
> could you post an self-contained example without React involved?

Please, provide an example without React involved

**Comment by deepak2431** [comment]
@FZambia Thanks a lot taking time to help. Would like to update that I have resolved the issue :)
