### ISSUE TITLE
Golang wasm client for sdk v5

### ISSUE THREAD

**Issue by gedw99** [centrifugal/examples#68]
hey all,

@FZambia hope all is well in your new home !! 

congrats on the new v5 api. It sure looks good from what I can see so far..

Do you think it’s possible with the new v5 sdk to do a golang wasm PWA style Client ? 

This is where we have the web manifest and service worker code . Then it’s just golang compilation to wasm and that’s basically it I hope :) 

protobufs and wasm might be a problem . Not sure as I have not yet deeply looked  into the new v5 sdk.

**Comment by FZambia** [comment]
Hello, thx!

TBH I do not understand what you mean when saying about v5 API - it's mostly the same we had before with some improvements and dropping legacy.

I am not sure about Go and WASM development in general, if you remember we had a prototype of centrifuge-go working in WASM - https://github.com/centrifugal/centrifuge-go/pull/68 - and it's very controversal, not sure I am ready to commit to it at this point - don't see enough interest from the community.

Do you suggest something different here though?

**Comment by gedw99** [comment]
All the problems with compilation and size will not be a problem nw.

gotip compiles wasm and wasi fine now. You don’t need tinygo which is slow to compile too.

so it’s probably worth revisiting that code and using the new v5 api which has no GRPC dependency, which is always a problem with wasm and browsers .

i don’t have time to dig into this due to work.

Web sockets and json will be way easier .

**Comment by FZambia** [comment]
> so it’s probably worth revisiting that code and using the new v5 api which has no GRPC dependency

No idea what you mean here, nothing changed in v4 -> v5 in regards to that. All changes outlined in [Centrifugo v5 release post](https://centrifugal.dev/blog/2023/06/29/centrifugo-v5-released)
