### ISSUE TITLE
Keycloak example question

### ISSUE THREAD

**Issue by HJK181** [centrifugal/examples#69]
Hi, this is more of a question than an issue: How would you obtain a channel JWT authorization in the Keycloak example? As there's no `token_hmac_secret_key` configured I'm wondering if 

1. That token should be created by Keycloak?
2. The `token_hmac_secret_key` should be configured additionally and a backend service should use it to create the JWT?
3. The connection token from Keycloak should already contain the `channels` claim and be reused as channel JWT?

Thx in advance.

**Comment by FZambia** [comment]
Hello!

Take a look how we start Centrifugo in Keycloak example:

```
docker run --rm -it -p 8000:8000 \
    -e CENTRIFUGO_ALLOWED_ORIGINS="http://localhost:5173" \
    -e CENTRIFUGO_TOKEN_JWKS_PUBLIC_ENDPOINT="http://host.docker.internal:8080/realms/myrealm/protocol/openid-connect/certs" \
    -e CENTRIFUGO_ALLOW_USER_LIMITED_CHANNELS=true \
    -e CENTRIFUGO_ADMIN=true \
    -e CENTRIFUGO_ADMIN_SECRET=secret \
    -e CENTRIFUGO_ADMIN_PASSWORD=admin \
    centrifugo/centrifugo:v4.1.2 centrifugo
```

The only token-related option is `CENTRIFUGO_TOKEN_JWKS_PUBLIC_ENDPOINT`. Centrifugo works with JWK standard (see https://datatracker.ietf.org/doc/html/rfc7517). Keycloak is JWK provider in this case. 

So answers:

1. Yes
2. No, token is only created by Keycloak, Centrifugo checks it using CENTRIFUGO_TOKEN_JWKS_PUBLIC_ENDPOINT
3. Tokens created by Keycloak are rather limited - it will be hard to add dynamic `channels` claim to them, so with Keycloak this claim is not really useful I think

**Comment by HJK181** [comment]
Maybe my question wasn’t clear enough. I already started Centrifugo with ‘ CENTRIFUGO_TOKEN_JWKS_PUBLIC_ENDPOINT`. I’m also able to connect my Keyclok unseres to the server and refresh expired tokens. However, I still don’t understand how I should now use Keyclaok as the backend to create a channel JWT for the logged in user.

Our users have a custom claim that we call `tenants`. A tenant is in the form `company.locale`. I now what my unseres to be able to subscribe to a channel called `company:chat`. 

How do I create the JWT with that channel? Keycloak doesn’t provide an API to sign a randomly created JWT, doesn’t it?

**Comment by FZambia** [comment]
Got it, I don't think Keycloak may give you enough flexibility to create subscription JWTs. At least I do not know how. It's fine for authentication. There are several ways in Centrifugo to authorize subscription access, but if you want to use subscription JWTs then most probably you better use your own backend to generate them. Centrifugo has an option to setup separate config for subscription tokens so it's possible to use Keycloak for authentication, but custom backend to generate channel tokens. See [Separate subscription token config](https://centrifugal.dev/docs/server/channel_token_auth#separate-subscription-token-config).

**Comment by HJK181** [comment]
That’s exactly what I was looking for, thx a lot.
